### ISSUE TITLE
Add gofmt to travis 

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#101]
Checking if code is properly formatted (go fmt) is at times very annoying.
We can automate the check.

**Comment by PaulBernier** [comment]
Rather than doing it in Travis after the chance is already pushed, I would recommend to have a git pre-commit hook that run gofmt so that non-formatted cannot be even committed.

Interestingly a quick research yielded this: https://golang.org/misc/git/pre-commit
