### ISSUE TITLE
Update assets and add suggested assets

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#102]
Assets should be managed in a map.  
A number of new assets have been suggested, and are added here.

**Comment by PaulBernier** [comment]
> [...] and are added here.

Forgot to include them? I don't see the new asset list?

**Comment by PaulSnow** [comment]
It is in the whitepaper... Here is the new (suggested) list:
```
PegNet, 		PNT, 		PNT
US Dollar, 		USD, 		pUSD
Euro, 			EUR, 		pEUR
Japanese Yen, 		JPY, 		pJPY
Pound Sterling, 	GBP, 		pGBP
Canadian Dollar, 	CAD,		pCAD
Swiss Franc, 		CHF,		pCHF
Indian Rupee, 		INR,		pINR
Singapore Dollar, 	SGD, 		pSGD
Chinese Yuan, 		CNY,		pCNY
Hong Kong Dollar, 	HKD,		pHKD
Tiawanese Dollar,	TWD, 		pTWD
Korean Won,		KRW,		pKRW
Argentine Peso,		ARS,		pARS
Brazil Real,		BRL,		pBRL
Philippine Peso		PHP,		pPHP
Mexican Peso		MXN,		pMXN
Gold Troy Ounce, 	XAU,		pXAU
Silver Troy Ounce, 	XAG,		pXAG
Palladium Troy Ounce, 	XPD,		pXPD
Platinum Troy Ounce, 	XPT,		pXPT
Bitcoin, 		XBT,		pXBT
Ethereum, 		ETH,		pETH
Litecoin, 		LTC,		pLTC
Ravencoin,		RVN,		pRVN
Bitcoin Cash, 		XBC,		pXBC
Factom, 		FCT,		pFCT
Binance Coin		BNB, 		pBNB
Stellar			XLM, 		pXLM
Cardano			ADA, 		pADA
Monero			XMR, 		pXMR
Dash			DASH,		pDASH
Zcash			ZCASH,		pZCASH
Decred			DCR,		pDCR
```

**Comment by MitchellBerry** [comment]
### Currencies:

A rough out-of-date-yet-mostly-accurate list of most traded by value today.

https://en.wikipedia.org/wiki/Foreign_exchange_market#Trading_characteristics

Make of that what you will. Most traded certainly doesn't necessarily mean most utility provided.

### Commodities: 

Oil, Gas, Copper missed the cut

https://www.thebalance.com/the-most-actively-traded-commodities-809314

### Cryptocurrencies: 

Won't comment on the cryptocurrency choices as it's bound to offend someone, but hope they are taken into consideration with the above.

### Entry size

Once the threshold is crossed extra additions are more a miner data problem than new addition problem. Niels did the maths elsewhere on number of available assets in one entry, but it's still all somewhat dependant on final design choices though.

**Comment by Cahl-Dee** [comment]
@nklomp please bring that math into this github issue so we have everything together. 

@PaulSnow let's make sure all requirements are detailed in the github issues so sufficient debate can happen here. White paper is good, but this is where the discussion should happen.

**Comment by MitchellBerry** [comment]
Ill just copy the comment here for posterity:

> So with 30 assets proposed now we have at least 600 bytes for the records, with some additional bytes for other stuff (haven't looked at the structure) like the DID and 64 bytes for a signature. Let's say 700 bytes

**Comment by Emyrk** [comment]
We currently do no have a data source for TWD and ARS. If we were to include those, we'd need to find a new currency data source

**Comment by Emyrk** [comment]
Merged in
