### ISSUE TITLE
Refactor miner into it's own object

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#122]
Currently the "miner" is just a function. This means you cannot stop/start or reference a miner.

The current miner will write an opr per thread, which is fine for dev, but in production we only want to write the best opr.

**Comment by WhoSoup** [comment]
Since each mining routine has a unique OPR, you want to submit all of them, up to 10 per directory block to maximize the potential payout. Submitting more than 10 seems unnecessary, so if you start more miners than that it should submit the best ten.

**Comment by Emyrk** [comment]
Yea, my first step was to separate miners into their own objects, my next step is to create an aggregator that only submits the best X.

I will make another issue to do that aggregation. This to me was a necessary step to support that better

**Comment by Emyrk** [comment]
Addressing Who's comment -> https://github.com/pegnet/pegnet/issues/126
