### ISSUE TITLE
Miner should only submit best X records

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#126]
Currently the miners submit the best OPR they find, so if you launch 15 miners, you get 15 OPRs. This is fine for development, but for production, we should really have an aggregator that only submits the best X records.

I don't know if submitting the best 1, best 2, or some algorithm based on identities is best. If anyone has any suggestions as the best way to handle OPR submission, I'm all ears.

My current though is to create an aggregator. Each OPR mined will be sent on a channel to the aggregator, at which it will only keep the top X. At minute 9, it submits the top X.

If someone wants to change the logic, they can change it in the aggregator, vs having to change miner logic.

**Comment by WhoSoup** [comment]
For milestone1, a simple aggregator that submits the top X is sufficient, though how many to submit should be left up to the user (via flag or something): 0 < X <= \# of miners

**Comment by Emyrk** [comment]
That was my initial thought as well. :+1:
