### ISSUE TITLE
API Endpoint: "performance"

### ISSUE THREAD

**Issue by sambarnes** [pegnet/pegnet#127]
In response to https://github.com/pegnet/pegnet/issues/117

Implement the following endpoint:

Method: "performance"

Parameters: 
- `"block_range"`
    - if not present, default to overall performance. Otherwise, must be one of the following:
    - a JSON object `{"start": START_BLOCK, "end": END_BLOCK}` where "end" is optional and defaults to current block (inclusive)
    - if negative values are used for `START_BLOCK` or `END_BLOCK`, it will take the block height that many behind the current directory block head
- `"id"`: the miner ID we wish to request statistics for

Response:
```
{
	"results": {
		"block_range": {
			"start": 201000,
			"end": 2012500,
		},
                "submissions": 1500,
		"rewards": 1337,
                "difficulty_placements": {
                        "1": 5,
			"5": 8,
			"10": 10,
			"25": 20,
			"50": 30,
			"100": 100,
			"250": 200,
			"500": 300,
			"1000": 400,
			"2500": 500,
			"5000": 750,
			"10000": 1000,
			"count": 1500,
			"sum": 125000,
                },
		"grading_placements": {
			"1": 5,
                        "2": 10,
			...
			"49": 28,
			"50": 30,
                        "count": 30,
			"sum": 750,
		},
	}
}
```

Example usage of results:
- `difficulty_placements["count"] / difficulty_placements["sum"` would give you the average rank for your hash power
- `difficulty_placements["10"]  / difficulty_placements["count"]` would give you % of submissions that were in the top 10 hash power

**Comment by sambarnes** [comment]
Branch: https://github.com/pegnet/pegnet/tree/PNT-127_PerformanceAPI/api
Handler: https://github.com/pegnet/pegnet/blob/PNT-127_PerformanceAPI/api/handlers.go#L18

**Comment by Emyrk** [comment]
PR: https://github.com/pegnet/pegnet/pull/133
