### ISSUE TITLE
Launch Check List

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#131]
We need to ensure a fair Launch.

Discuss the issues here, update the PegNet Readme (serves of public notification about process)

**Comment by PaulSnow** [comment]
See the Launch Plan here:

https://docs.google.com/document/d/1GZ6sm7jMTQXyz0j0YIzUZbyFg8DzCIXR9EHyx7tNB3c/edit

**Comment by PaulSnow** [comment]
Should decide how much we should put in the repository.  I'd say once the details are more settled (dates) then we should add to the readme or maybe make a docs folder and keep in the repository?

**Comment by Cahl-Dee** [comment]
Completed and reviewing with the Factom Protocol marketing committee to see how they can support.
