### ISSUE TITLE
Include script to create Pegnet chains

### ISSUE THREAD

**Issue by drkatz** [pegnet/pegnet#136]
Currently if the Pegnet daemon is started and the OPR chain(s) does not exist a error is occurs and the daemon exits:
```
FATA[0032] An error in OPR was encountered               caller="pegnet/opr/grading.go:147" error="Missing Chain Head"
```
For those testing on a fresh local Factom network it would be helpful if the Pegnet project either included a script in `initialization` to create the chains, or just automatically created them. Otherwise the user has to manually create them via CLI or other means.

**Comment by drkatz** [comment]
The reference branch & PR for this issue is https://github.com/pegnet/pegnet/pull/134

**Comment by PaulBernier** [comment]
Isn't `go run initialization/main.go` what you are looking for?

**Comment by drkatz** [comment]
Thanks, this solved my issue @PaulBernier
