### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#15]
We need some serious work done on the documentation.  I've written a bunch of theory, and have discussed various aspects of the protocol, but more user documentation and other documentation needs to be identified and written.

Edit (via @Cahl-Dee ):
Documentation needed before pM1 launch to include...
- [draft] clear miner documentation
-- how to setup
-- brief overview of what the mining is doing
-- identity performance of miner
-- mining benchmarks/suggested specs
- [pending] CLI tool documentation mainly around key management. Include links to guides for setting up factom walletd
- [complete] ~~Greg Forst has requested a narrative/story around Pegnet - "I am newer to the specifics of Pegnet and want to take this to all our channels (PR, social etc...) but I need more clarity on the narrative/story we are telling with pegnet. The technical description is great but what does it solve, enable, use cases, better than X etc...  I need to feed a story with the product and as you know other stable coins exist"~~

Edit 2 (via @Cahl-Dee ):
Draft docs are available [here](https://docs.google.com/document/d/1MVK-iR3V6S7IWNAITxaU5EWAPU41kP-Jnm35Cse9-Vc/edit)

Edit 3 (via @Cahl-Dee ):
All docs are live on the github wiki here: https://github.com/pegnet/pegnet/wiki

**Comment by sambarnes** [comment]
As far as protocol documentation, I've started a technical overview / design document here: https://docs.google.com/document/d/1nr0G1Qc7aZg880ZuDcvBqIt-4WIBSuUBp5CyZZ2ayco/edit#

Just really slowly adding to it as I learn more about how the parts are working together

As far as user documentation goes, I can start some readme's in the repo for running the miner and whatnot

**Comment by WhoSoup** [comment]
I'm going to write a blog post on PegNet at some point but I'm waiting on things to settle down first so I can go into technical details. Aiming for an explainer to newcomers about what pegnet is, how it works, and what it does.

**Comment by Cahl-Dee** [comment]
@PaulSnow can you edit your initial comment describing exactly what the requirement of this ticket is? What are we looking for? Documentation for who (not @WhoSoup)? What should the reader be able to achieve after reading these docs?

**Comment by Cahl-Dee** [comment]
We will be working on this documentation next week while the mining test is running.

Important that we complete this early in the week because we need to get it out to people who want to be involved.

**Comment by DavidChapman77** [comment]
FAQ is here.  https://docs.google.com/document/d/1krBbcd71RAMp6Brc3CNfXMUBFMitFY9y9IV5jRLUV_s/edit

Please add to / improve it.

**Comment by Cahl-Dee** [comment]
FAQ and Docs have
