### ISSUE TITLE
Provide Miner balances

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#16]
Need to write code to scan the Oracle Mining Records chain and print the payouts for all the miners so they can see what they have from mining.

**Comment by WhoSoup** [comment]
relevant discussion from discord:


![image](https://user-images.githubusercontent.com/34172041/61704580-4f389380-ad44-11e9-9b90-e19e81c31404.png)

**Comment by Emyrk** [comment]
Are we still keeping this ticket alive?
Or are we deferring this to the FAT daemon

**Comment by Emyrk** [comment]
We are pushing balances to the FAT daemon. Tracking balances requires tracking conversions, burns, txs, and coinbases. 

Let's close this and discuss over -> https://github.com/pegnet/pegnet/issues/117
