### ISSUE TITLE
Validate DBHeight is as expected & Fix rewards to be in 1e8 fixed point

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#165]
The dbht in the opr is not being validated
Make rewards X * 1e8

**Comment by WhoSoup** [comment]
the dbht in the opr is validated when parsing the eblock: https://github.com/pegnet/pegnet/blob/9a4c96510cef3cb3630d9fc8b4015f3a58e49049/opr/grading.go#L174
