### ISSUE TITLE
OPR grades aren't normalized

### ISSUE THREAD

**Issue by AroundTheBox** [pegnet/pegnet#168]
As far as I can see in the proposal paper there's no normalization for OPR grades, meaning high dollar value assets have significantly more weight.

Assume there are only two assets with averages for the 50 highest POW OPR records as follows.
Bitcoin: $10,000
Euro: $1.10

Alice submits an OPR with the following.
Bitcoin: $10,005
Euro: $1.10
Alice's grade is 5^4 + 0^4 = 625

Bob maliciously submits an OPR with the following:
Bitcoin: $10,000
Euro: $2.10
Bob's grade is 0^4 + 1^4 = 1

Bob gets a much lower grade despite submitting a malicious entry showing the Euro value to be worth almost twice as much. To fix this the OPR grades could normalize to the average before squaring.

**Comment by PaulBernier** [comment]
The grades are actually normalized in the code: https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L53
This would need to be updated in the proposal paper @PaulSnow .

**Comment by AroundTheBox** [comment]
Thank you.
