### ISSUE TITLE
Grading bugs

### ISSUE THREAD

**Issue by PaulBernier** [pegnet/pegnet#169]
I believe there are a few important bugs in the grading algorithm that let invalid OPRs be selected. 

The crux of it is in the following `for` loop, that does a couple of odd things: <https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L212>

- https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L216 this `continue` statement actually allows (even help!) entries with invalid previous winners to be validated. I believe it should `continue` to the outer loop
- https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L218 this and the few statements after should not be in this loop, they have nothing to do with `WinPreviousOPR`
- https://github.com/pegnet/pegnet/blob/develop/opr/grading.go#L215 this compares the previous winners of the current OPR with the **previous** winners of the previous oprblock. I believe it should compate it simply with the winners of the previous oprblock.

**Comment by Emyrk** [comment]
Did @WhoSoup Resolve this issue?

**Comment by PaulBernier** [comment]
I believe it did address all the issues, yes
