### ISSUE TITLE
Print notification when LXRHash file is being calculated

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#170]
Right now the console is just blank for 10+ minutes with no output while the hash file is being generated. We can either turn LXRHash's verbose option on, or at least print out console output letting people know when it starts and when it ends

**Comment by Cahl-Dee** [comment]
Agree, this is a bit obnoxious.

**Comment by WhoSoup** [comment]
this has been implemented

**Comment by Emyrk** [comment]
Can probably be refined later
