### ISSUE TITLE
Design Transaction Structure and Execution Rules

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#18]
Create the conversion transaction that allows a user to convert assets from one pegged token to another.

CoS:
- A design is produced that is able to be implemented
- Tickets are created for all work items needed to execute the design

**Comment by Cahl-Dee** [comment]
related discussion that should be considered during design #190

**Comment by Emyrk** [comment]
> So that a user can try to convert X (at most) PNT into Y pXBT. If they overestimated the amount of PNT needed, I don't think they should be punished for that and have the difference burned

I think the reverse logic could be made though. If BTC is currently $10,000, and I say 
```
10,000 pUSD -> 1 pBTC
```

If the BTC price goes down, then I get a cheaper price and more BTC. How do we know the user wants ONLY 1 BTC? What if they want >= 1BTC, but nothing less?

**Comment by Cahl-Dee** [comment]
>"type": <TOKEN TICKER (no "p" prefix): string>,

Are we gaining anything from not including the "p" prefix? Unless there is significant gain, we should include it. The tx/conversion is not of USD but of pUSD.

**Comment by sambarnes** [comment]
> @Cahl-Dee :  Are we gaining anything from not including the "p" prefix?

We get transaction payload portability across mainnet and testnets. Is that worth it? Maybe maybe not. Just makes things easier so we don't have to be putting conditionals all over the place saying "if testnet, use t. else use p"

**Comment by WhoSoup** [comment]
> Just makes things easier so we don't have to be putting conditionals all over the place saying "if testnet, use t. else use p"

that's something we need to rip out of the code anyway. repost from discord:
![image](https://user-images.githubusercontent.com/34172041/64114276-e144aa80-cd8c-11e9-995d-ba46d6b093e6.png)

**Comment by Cahl-Dee** [comment]
Complete, broken into #283 #287
