### ISSUE TITLE
Polling call failure crashes the miner

### ISSUE THREAD

**Issue by MitchellBerry** [pegnet/pegnet#182]
A better way to do this is perhaps reusing the last recorded values? 

Indefinitely isn't ideal, but for a certain number of retries it much better for the miner than simply returning 0 or crashing. 

Trying to find the middle path between miner writing pointless entries for hours or writing none simply because of momentary network issues. 

Is a subset of the errors in mentioned in: https://github.com/pegnet/pegnet/issues/125

**Comment by WhoSoup** [comment]
> A better way to do this is perhaps reusing the last recorded values?

relevant discussion: https://github.com/pegnet/pegnet/issues/11
