### ISSUE TITLE
Whitepaper refinements

### ISSUE THREAD

**Issue by Cahl-Dee** [pegnet/pegnet#191]
Whitepaper - https://docs.google.com/document/d/1yv1UaOXjJLEYOvPUT_a8RowRqPX_ofBTJuPHmq6mQGQ/edit

There have been requests to refine the whitepaper regarding changes that were made during implementation as well as for clarity. The following specific requests have been made:
1. put in some commentary about why there is suddenly something about LXR hashes in the section about mining. A layman will have no chance of understanding.
2. check that the listed currencies are correct (Paul mentioned the importance of the Taiwanese dollar)
3. update some figures to make them easier to understand (particularly the conversion examples)
4. make sure the development plan is either up to date, removed or points to a place where the plan is dynamically updated
5. go through to make the language clearer
6. resolve any open comments on the google doc

**Comment by PaulSnow** [comment]
2.  The Forex source we are using in the reference PegNet right now does not support the Taiwanese dollar, so what we need is a good source for its market price to support it.  For now, we will not support, but we would like to support it in the future.

3. We could use better figures, but this is not my strong suit.  Would be happy to work with anyone on designing better figures.

5. We need suggestions in the document where people feel the language needs to be improved.

**Comment by hinamatsuri85** [comment]
I made a suggestion for a how the figures that show conversion could look. I cannot do it in suggestion mode, so I have used the version history feature on the first of the figures.

**Comment by hinamatsuri85** [comment]
Now I also finished going through all of the wording. I need Paul or whoever co-owns the document to go through and approve - or just tell me that everything is probably fine and I'll do it myself ;)
However in addition to the point about LXR graphs above, there are a few additional places I need input, either because I do not have the needed technical knowledge or because the original writing was quite convoluted.
