### ISSUE TITLE
Add rate calculation for conversions

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#193]
Before we add conversions, we need the opr record to be able to calculate an exch rate for any pair.

I was going to implement it as such, where `(FCT_USD)` is the rate in the opr for FCT.
```
x pFCT -> z pXBT
1. x pFCT * (FCT_USD) = y pUSD
2. y pUSD / (XBT_USD) = z pBTC
```

So in the example of this OPR: https://testnet.factoid.org/entry?hash=5c7b221940d1f2931c5739f567f488b58bb8c676af8c45216cef901552fd69ac

Rates
`(FCT_USD) = 3.9118`
`(XBT_USD) = 10004.4625`

`5 pFCT * 3.9118 / 10004.4625 = 0.00195502756 pBTC`

**Comment by WhoSoup** [comment]
Looks good!

**Comment by Emyrk** [comment]
See this: https://github.com/pegnet/pegnet/issues/196

I went with float64s in the end. It's the most accurate, and is consistent as long as we stick to IEEE standard. I always truncate vs round in the amounts, so error will always work against you and lose tokens. The amount lost is very small, and inevitable. It is impossible to game because of truncating

**Comment by Emyrk** [comment]
The final implementation: https://gist.github.com/Emyrk/68f98b7aca65208269dded185682c972#file-exchange-go-L39-L60
