### ISSUE TITLE
Basic validation of `minerid` field

### ISSUE THREAD

**Issue by PaulBernier** [pegnet/pegnet#195]
During grading the minerid/FactomDigitalID field is not validated at all and even if it's missing (nil) the OPR will be judged valid.

Even though the digital identity is not yet deeply used we should have a minimal validation for it to be non null and non empty string.

**Comment by MitchellBerry** [comment]
from what's been said earlier it should just be alphanumerics along with `_` or `-`?

**Comment by WhoSoup** [comment]
> From what's been said earlier minerid should just be alphanumerics along with `_` and/or `-`?
> 
> The miner should panic on startup for anything invalid.

This is indeed the case already: https://github.com/pegnet/pegnet/blob/a5655d68ca35017a952aed9845f5c3fc20f32101/cmd/root.go#L125-L133

At the moment, the minerid field in the OPR is just for internal tracking for miners themselves and has no other relevance until DIDs are implemented.

I'm okay with the possibility of it being nil or empty until then.

**Comment by Emyrk** [comment]
Yea, the coinbase is the real identified at the moment imo.

**Comment by PaulBernier** [comment]
Fair enough. Was just bothering me a tiny bit that we have a field completely unvalidated, but that's fine.
