### ISSUE TITLE
Use SHA256 to calculate OPR hash

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#199]
Came across this while taking a stab at implementing self-reporting of difficulties. At the moment, LXRHash is very expensive to run. 

I'm using the numbers of my personal rig (which benchmarked as one of the fastest), but the ratios should still hold true:
1. The cost of calculating the LXRHash from the entry is **3,792,216** ns
2. The cost of calculating the difficulty is **188,310** ns 
3. The cost of calculating the SHA256 from the entry is **9,010** ns

At what point does it become a problem? 

| \# records | LXRHash | SHA256 |
|---|---|---|
|50| ~0.2 seconds | 0.0004 seconds | 
| 200 | ~0.75 seconds | 0.002 seconds | 
| 1000 | ~4 seconds | 0.00901 seconds |
| 5000 | ~19 seconds | 0.045 seconds | 
| 10000 | ~40 seconds | 0.09 seconds |

All in all, it's not the end of the world for miners but it does have consequences. If someone decided to flood OPRs, miners could lose up to a minute of mining time, giving the spammer a potential headstart to generate more OPRs and influence the average. 

For new nodes it makes the syncing process terrible. If PegNet runs for a year (52,560 blocks) with around 200 OPRs per block (probably a low end), we have 10,512,000 OPRs to grade. That's 11 hours of just calculating the OPR hash in order to sync the chain. (Since we self-report the difficulty, we only expect an average of 50 OPRs per block for that, which comes out to ~8 minutes.)

We need LXR Hash to calculate the difficulty since that's the PoW Hash, but we don't need LXR for the OPR Hash. Sha256 is just as good. That would make the formula for difficulty:

`difficulty = LXRHash(Sha256(content) | nonce)[:8]`

And since mining only calculates the opr hash once, there would be perceptible change. 

For 52,560 blocks at 200 OPRs, it only takes around 2 minutes to calculate the Sha256 hashes. (+8 minutes in difficulty calculation)

Miners would be able to process the new DBlocks in less than a second even if there are thousands of entries.

**Comment by Emyrk** [comment]
I think this is totally valid. :+1:

**Comment by Emyrk** [comment]
closed https://github.com/pegnet/pegnet/pull/200
