### ISSUE TITLE
Add  Alpha Advantage as a data source

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#203]
https://www.alphavantage.co/support/#api-key

**Comment by WhoSoup** [comment]
Their API only seems to allow exchange rates for a single pair, meaning we'd have to make 30 requests to get all USD/X pairs. Their standard volume for free keys is 5 a minute and 500 a day. We'd need a burst of 30 every 10 minutes and 4,320 a day at minimum. Their cheapest plan is $30 a month.

![image](https://user-images.githubusercontent.com/34172041/62527376-4d3dfc80-b83b-11e9-86d7-1f31fecf55a4.png)

**Comment by MitchellBerry** [comment]
Out of the box all api clients interactions should be free. Have serious philosophical disagreement with supporting these useless walled gardens charging money for the current price of X

Everyone should have access to mining regardless of means, these tools/endpoints should be purged from the codebase.

**Comment by WhoSoup** [comment]
> Out of the box all api clients interactions should be free. Have serious philosophical disagreement with supporting these useless walled gardens charging money for the current price of X
> 
> Everyone should have access to mining regardless of means, these tools/endpoints should be purged from the codebase.

i agree, though i have concerns about the availability of good and free apis in this regard, especially ones that have the desired list of assets

**Comment by Cahl-Dee** [comment]
Didn't see interest in this. Feel free to reopen if you want it :-)
