### ISSUE TITLE
Default source of precious metal price is brittle

### ISSUE THREAD

**Issue by PaulBernier** [pegnet/pegnet#204]
The current default source for precious metals price is to web-scrap the Kitco website. Web-scraping is brittle, if Kitco changes one html tag tomorrow the whole PegNet mining is threatened. Web-scrapping is acceptable in dynamic context where it's possible to quickly update the software to a changing webpage, which is quite the opposite of mining software  distributed all around the world. I believe pegnet core miners should only rely on APIs, APIs are formal contracts while html pages are not.

I see two potential solutions to move away from that web-scraping:
1. Change the default to openexchangerates API, as it has the 4 precious metals we are tracking.
2. Give up on Palladium and Platinum, and get Gold and Silver from apilayer

**Comment by PaulSnow** [comment]
I like 1.

**Comment by Cahl-Dee** [comment]
Update: we agree on dropping Palladium and Platinum.
