### ISSUE TITLE
CLI Wallet Commands for TXs/Conversions

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#21]
Allow the construction and execution of pegnet conversions and transactions.

**Comment by sambarnes** [comment]
I believe the better way forward is to make pegnet a single binary with multiple options like geth does. This will allow us to do things like:

`pegnet` for normal node/validator running
`pegnet --miners=8` for a node that mines as well

and then while one of the above are running:
`pegnet get balance ADDRESS` can be run to send an RPC command to the local node

This will lower the number of repos we need to have, and also allow users to only have to install a single binary.

**Comment by Cahl-Dee** [comment]
@sambarnes @PaulBernier @PaulSnow Please provide clear requirements as to what will be delivered as part of this issue. It should all be rolled up and placed in the first comment once it has been decided.

**Comment by Cahl-Dee** [comment]
As Sam mentioned in Discord, this is for creating transactions/conversions from the CLI. Transactions and conversions are later milestones and thus this Issue is being pulled from pM1.

**Comment by Cahl-Dee** [comment]
this is addressed in separate issue
