### ISSUE TITLE
Add version number to opr entry as external ID

### ISSUE THREAD

**Issue by Cahl-Dee** [pegnet/pegnet#217]
Via AroundTheBox on Discord:
> Does the current spec include a "miner version #" type field? If not I think we should consider having one and enforcing the most recent version (after block height XYZ) for an OPR to be accepted
> That would help solve the problem of getting stuck in a suboptimal equilibrium. For example, the default miner uses an API that becomes unreliable or inaccurate. The community wants to move to a better data source or even better a combination of data sources. They can't incentivize anyone to do so because they would become an outlier until everyone else has moved as well.
> But if you released "miner v2" and only accepted OPRs identifying as using "v2" after a particular block height, everyone has the incentive to change. You can of course cheat and just call your "v1" miner "v2", but you'll still be incentivized to update your data source to avoid being an outlier.

...

>Importantly we have to reject OPS that aren't claiming to be the current version.

**Comment by Emyrk** [comment]
Added single byte to extid[2]
