### ISSUE TITLE
Update Default Data Sources

### ISSUE THREAD

**Issue by Cahl-Dee** [pegnet/pegnet#225]
Default sources should be https://www.freeforexapi.com/ and https://docs.quandl.com/docs/getting-started

With the following implemented as well: https://1forge.com/forex-data-api/pricing

While individuals are welcome to use other sources after checking with the provider around legality, the above ToS's appear to allow usage along the lines of pegnet.

I am not a lawyer and am not giving legal advice :-)

**Comment by Emyrk** [comment]
Quandl is daily rates, not live

**Comment by Cahl-Dee** [comment]
@sambarnes is working on collecting a list of Sources here https://docs.google.com/spreadsheets/d/1KX2Aiou6WOk7zrD0bo52Y5qW9aaMzCNMAUqXl1nE7F8/edit#gid=0
