### ISSUE TITLE
Should not put a public FCT address in the defaultconfig.ini

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#246]
The config file for the PegNet should not have a FCT address specified for the coinbase address, because many users will make a mistake, and mine to an address they do not control.

Changed the config file, and added a quick error check.

**Comment by PaulSnow** [comment]
Also error reporting was lacking.  Added better explainations to the config file and to error reporting.

**Comment by PaulSnow** [comment]
Also fixed the config.ini vs defaultconfig.ini confusion.
Now we open the config.ini if that's what the user gives us.  But if that isn't there, we open defaultconfig.ini

This way the user can keep both the default and a config that they want in the .pegnet directory.  And we don't break people using defaultconfig.ini now.

**Comment by Cahl-Dee** [comment]
Already have PR for this @PaulSnow please link it to this
