### ISSUE TITLE
Minimum capitalization

### ISSUE THREAD

**Issue by Cahl-Dee** [pegnet/pegnet#267]
This issue is first for the discussion of if we want a minimum capitalization of FCT->pFCT before enabling conversions. If it is agreed that there should be, it will then be left open and blocking the release of pM2 until the capitalization has been met.

**Comment by DavidChapman77** [comment]
Yes, we need a minimum capitalization.  Not having it risks the sanctity of the network in my opinion.  I propose that it be a minimum of $100,000.  I also suggest that once the minimum capitalization is met, there is a certain block delay (maybe 3 days worth) prior to pricing and conversions kicking in rather than immediate.  This reduces potential for gaming from different directions.

**Comment by PaulSnow** [comment]
The idea here is to get enough parties with enough capitalization in the PegNet assets that a "reasonable" starting value of PNT is established, and enough holders to prevent massive abuse of conversions early on.  We do have quite a bit of PNT concentrated with one powerful miner, but we would like to have distribution of the pFCT over as many parties as possible prior to conversions.

Conversion of FCT to pFCT will be the easiest way to get  a position established in the PegNet during the launch phase of the protocol.  This is under simple user control, and will allow parties into the PegNet and thus into all the other pegged assets without permission, large sets of mining rigs, and other complications.

At this point in time, capitalization of $100,000 prior to conversions is the current nomination for the network.

**Comment by PaulSnow** [comment]
> Yes, we need a minimum capitalization. Not having it risks the sanctity of the network in my opinion. I propose that it be a minimum of $100,000. I also suggest that once the minimum capitalization is met, there is a certain block delay (maybe 3 days worth) prior to pricing and conversions kicking in rather than immediate. This reduces potential for gaming from different directions.

I am not sure we need 3 days, but at least 24 hours and/or the scheduled date for conversions.  I do believe getting to $100k is likely to happen more than 3 days prior to having the infrastructure, code, and testing being ready.

**Comment by DavidChapman77** [comment]
>> I am not sure we need 3 days, but at least 24 hours and/or the scheduled date for conversions.

We need at least 72 hours so we can effectively communicate that conversions are going live at X block.  Think of this as being a second fair launch.  We don't want anyone saying, "We weren't given enough time to get ready and X, Y, and Z entities took advantage of the lack of players."

**Comment by PaulSnow** [comment]
Sure, noticed is good.  But unlike mining (that requires significant upfront work) conversions will be pretty simple.  Run a simple conversion wallet, see your balances, choose your conversions and go.

As I said, I think we can do 3 days (72 hours) and we can tell everyone the block height.  And if we didn't get the 100k bar, we could delay.  I guess that is what I am saying, that the 100k bar isn't necessarily required 72 hours ahead of time.

**Comment by Cahl-Dee** [comment]
Seems we've agreed on 100k capitalization. Moving to done
