### ISSUE TITLE
Initialization script does not parse FactomdLocation and WalletdLocation from the config file

### ISSUE THREAD

**Issue by afenrir** [pegnet/pegnet#277]
The initialization script used to bootstrap a local network does not parse FactomdLocation and WalletdLocation from the config file. This is problematic, as it prevents PR #260 from using the config file to specify the location of Factomd and Walletd for use within Docker. 

https://github.com/pegnet/pegnet/blob/7b3aac9847c1f62801a09d540ec5d9512332cba3/initialization/main.go#L62

**Comment by WhoSoup** [comment]
fix has been merged to develop, considering this issue resolved
