### ISSUE TITLE
Tx Creation: a custom CLI or a GUI for FAT command construction

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#285]
Allow people to do conversions and transactions via command line. This issue depends on #283 and #284 to be completed first.

**Option A:**
A very simple cli utility to write entries to the tx chain in the FAT specific format outlined in #283.

* Balances can be checked before submissions to prevent sending transactions guaranteed to fail
* Determine how to handle private keys in a safe manner
* Entries need to be signed

**Option B:**
A simple webpage or desktop app is able to be run that lets a user easily construct FAT-cli commands to transact/convert their assets

**Comment by Cahl-Dee** [comment]
This ticket to be converted to a utility for constructing FAT cli commands for the average user. Note the level of technical know-how that miners have.

@sambarnes
