### ISSUE TITLE
FATd Integration

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#287]
Repost from discord/#fat-integration channel:

* FATd provides us a framework for tracking entries and chains. it takes care of the job of syncing with factom nodes and feeding entries into a job queue ("applying" it to the database)
* each token in fatd has its own dedicated sqlite database, meaning we are going to have to create our own altered db schema to accomodate the pegnet tokens
* functionality for tracking multiple things does not come out of the box. @AdamSLevy has offered his assistance in creating functionality for fatd to track the fct chain (to register burns) which does not yet exist
* the FAT team and I agree that it would be preferrable to not have API reliance, meaning a fatd node shouldn't need a pegnet node to run and vice versa. this means that some things may end up being implemented twice. i have created a visual representation of the dependence we're looking at here:

![image](https://user-images.githubusercontent.com/34172041/64334402-c23a5880-cfd8-11e9-9df3-a9e33f9545a6.png)
(please note that the miner requiring the balances is only needed to determine the value of PEG for oprs. once PEG is listed at exchanges, that dependency will fall away)

The challenges for this will be:
* making sure that fatd and pegnet are on the same page when it comes to configurations like **activation heights** 
* making sure that the balances use the same math as pegnet in order to avoid any differences stemming from rounding errors

If issue #286 is finished, then this will significantly aid development.

**Comment by Cahl-Dee** [comment]
This has been broken into separate sub-tickets... see:
#283 #293 #291 #284 https://github.com/pegnet/pegnet-compose/issues/3 #296 #286 #285 #268
