### ISSUE TITLE
FATd: Add Factoid Blocks & Transactions to factom library

### ISSUE THREAD

**Issue by sambarnes** [pegnet/pegnet#291]
From #287 
> @AdamSLevy has offered his assistance in creating functionality for fatd to track the fct chain (to register burns) which does not yet exist

Conditions of Satisfaction:
- Factoid Blocks and Factoid Transactions are able to be fetched using the FAT factom library
- FCT --> pFCT burns are able to be implemented (in #284 )

**Comment by AdamSLevy** [comment]
I will be breaking github.com/Factom-Asset-Tokens/fatd/factom into its own repo and go module at github.com/Factom-Asset-Tokens/factom.

I will start working on implementing these features later this week.

**Comment by AdamSLevy** [comment]
The factom package has now been moved into its own repo and module to allow it to be improved and used more independently of fatd.

Repo: https://github.com/Factom-Asset-Tokens/factom
Docs: https://godoc.org/github.com/Factom-Asset-Tokens/factom

**Comment by Emyrk** [comment]
We have enough functionality in https://github.com/Emyrk/factom to continue.

The rest of this issue should be tracked and completed in the factom lib
