### ISSUE TITLE
GoLang implementation of conversion math

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#293]
Conversion calculation was discussed and ended up with https://gist.github.com/Emyrk/68f98b7aca65208269dded185682c972#file-exchange-go-L39-L60.

We should create a reference module for the calculation so wallets and other libs have a reference to base theirs off of. A proper set of vectors and unit tests need to be included.

Cos:
- Importable module to compute conversion given the usd rates and the input amount

**Comment by sambarnes** [comment]
The work for this module is being done within the following branch: https://github.com/pegnet/pegnet/compare/develop...conversions_math_module

As @WhoSoup mentioned in another thread (that i don't recall the location of currently) the naming of the functions `ExchangeFrom, ExchangeTo` was slightly confusing and didn't convey the behaviour off the bat. I'm not sure if this is an improvement though?

```
// MinimumInputNeeded tells us how many `inputType` tokens are needed to create the requested amount of
// 'outputType` tokens.
func (o OraclePriceRecordAssetList) MinimumInputNeeded(inputType string, outputType string, requestedOutputAmount int64) (int64, error) {...}

// MaximumOutputPossible tells us how many `outputType` tokens can be created from a given number of `inputType` tokens.
func (o OraclePriceRecordAssetList) MaximumOutputPossible(inputType string, availableInputAmount int64, outputType string) (int64, error) {...}
```

**Comment by Emyrk** [comment]
@sambarnes I'm not sure about the naming, but I think you should have to pass in the rates vs it being on `OraclePriceRecordAssetList`. The new module package returns `uint64` as the conversion rate, so instead of `inputType string`, it would be `inputRate uint64`

**Comment by WhoSoup** [comment]
> I'm not sure if this is an improvement though?

these names are definitely an improvement but to reiterate my point [from the other thread](https://github.com/pegnet/pegnet/pull/197#discussion_r312856149): we don't need two separate functions for this. we only need one: `exchange(amount, from_type, to_type)`

Type A of "convert all X to Y" would be `exchange(amount, x, y)`
Type B of "how much X do I need to get Y" would be `exchange(amount, y, x)`

**Comment by Emyrk** [comment]
> > I'm not sure if this is an improvement though?
> 
> these names are definitely an improvement but to reiterate my point [from the other thread](https://github.com/pegnet/pegnet/pull/197#discussion_r312856149): these two functions are currently just wrapper functions for `exchange(amount, from, to)`. We don't really need the wrapper functions, we just need `exchange` to be public

Yea, that will be enough. I wrote the extra method definitions around Exchange because my unit tests were already written for them :laughing:. And I just wanted to get the math down, not the final release.

**Comment by sambarnes** [comment]
@Emyrk 
>  but I think you should have to pass in the rates vs it being on OraclePriceRecordAssetList

I agree. Only had it that way because thats what you did in the gist you posted and figured there was a good reason for it. I'll change it

**Comment by Emyrk** [comment]
> @Emyrk
> 
> > but I think you should have to pass in the rates vs it being on OraclePriceRecordAssetList
> 
> I agree. Only had it that way because thats what you did in the gist you posted and figured there was a good reason for it. I'll change it

Yea sorry. The gist really was just to show the math. You can kinda toss everything outside of it. I just wanted to provide context too.

**Comment by sambarnes** [comment]
Alright I have simplified the module to the bare minimum. https://github.com/pegnet/pegnet/compare/develop...conversions_math_module

Now need to write a ton of tests to exercise it. Any suggestions on definite edge-cases to try are welcome.

Probably not worth making something that will randomly generate new tests as that will just require reimplementing the module that we are testing in the test

**Comment by Emyrk** [comment]
@sambarnes When I did this, I wrote tests that checked going both ways through a tx.

| Tx | From Currency (uint64) | Conversion Direction | To Currency (uint64) |
|----|:----------------------:|:--------------------:|----------------------|
| 1  | Given `x`              | --->                 | Computed `y`         |
| 2  | Given `y`              | --->                 | Compute `x'`         |
| 3  | Given `x'`             | --->                 | Compute `y'`           |

I used random rates for `x` and `y`. Because of error, `x != x'`, but you know the maximum error is the maximum ratio between x and y:
```
// Max is not a Golang native function, you'll have to write one
maxerror := Max(from/to, to/from) + 1 // Truncation adds an extra '1' to the error
```

So when making these 3 conversions for a test.
1. `math.Abs(x-x') < maxerror`
2. `y` == y' (pretty sure about this one)

Additionally, I think we should document some errors as vectored tests. Storing `x`, `y`, `x'`, and `y'` in some json format so anyone writing this conversion math has some vectors they can include in their test suite to ensure not only are the conversions correct, but the error in the conversions are also correct.

I did that here: https://github.com/pegnet/pegnet/blob/312c3847dd4325b5d11727ae6eb50d8d4c3b4be7/opr/assetList_test.go#L424-L430

**Comment by Emyrk** [comment]
Also, I doubt we will ever go over int64 for the conversion quotes, but you can make a `BigInt` from `uint64`:

https://play.golang.org/p/X0HACNn0pGG
```
big.NewInt(0).SetUint64(x)
```

We should just do it correctly.

**Comment by sambarnes** [comment]
Good idea with converting back and forth for the tests. I have implemented and pushed a set of tests that does just that. I will need to change the vectored tests to plain JSON so that they can be easily copy-pasted when someone implements this in another language.

For the set of randomly generated tests, I used random `uint64`s for the `xRate` and `yRate`, and a random `int64` between 0 and 1 billion units (`[0, 1e9 * 1e17)`) for the `x` amount. This 1 billion figure was included to avoid overflows and is completely arbitrary. Any suggestions on a better value would be appreciated.

One small detail though. In your message, you claim `y == y'` however I found this to not be the case. There many conversions where `y != y'` but the error was always within the expected maximum. Perhaps this is an implementation bug? I will try to investigate further

**Comment by Emyrk** [comment]
@sambarnes Hmm. Can you provide a vector for when `y != y'`. I figure that should hold, but I can check my math. I recalled those rules mostly from memory.

As for random uint64s, I don't see that being an issue, but limiting it to `rand.Uint64() % (1e5*1e8)` means your USD quotes are always going to be sub 100K. That is what I have done for a few tests because the regular random was always incredibly large, and outside our normal space.

Also I see you do this at some points:
```
int64(math.Abs(float64(x-y)))
```

I'd recommend implementing your own quick `Abs(v int64) int64` function, as converting to a float and back causes some errors when the numbers have a lot of significant digits. Plus I'm sure there is some truncation errors that crop in too: https://play.golang.org/p/BR73aXSQSoV (if you play with the limit of the random numbers, you can differences other than `1` and `-1`).

**Comment by Emyrk** [comment]
Also @sambarnes, if you want to open the PR as a draft against develop, it would make linking to lines in the review a bit easier

**Comment by sambarnes** [comment]
https://github.com/pegnet/pegnet/pull/317

As for an example vector that breaks the `y == y'` assertion:
```
xRate: 1513206842612
yRate: 847513007339

x1: 14611319475495699
x2: 14611319475495698

y1: 26088034541594034
y2: 26088034541594032
```

**Comment by Emyrk** [comment]
Another comment. I see you are using the wrong inputs to the `maxConversionError`. I should have bee a bit more clear. You have:
```
maxConversionError(x1, y1)
```

You should be using the rates, not the values. So
```
maxConversionError(xRate, yRate)
```

An example. If `xRate = 1` and `yRate = 100`, then `yRate/xRate = 100`.  That is the max error. So:
```
// Since 100X = 1Y
x1 := 99
y1 := Convert(x1, xRate, yRate) // y1 is 0, since 99 is not enough to get 1 Y
x2 := Convert(y1, yRate, xRate)  // Since y1 is 0, x2 == 0

// so x1 - x2 == 99, but the max error we allow is 100, so this is ok
```

**Comment by sambarnes** [comment]
@Emyrk gotcha, yeah I just saw your message only used x and y so I assumed you meant the values x and y that you had already been using. I should have double checked if that actually made sense though

**Comment by Emyrk** [comment]
@sambarnes I should have been more clear with the rates. I was using `x` and `y` a bit loosely. I'll look into the `y == y'` assumption.

**Comment by Emyrk** [comment]
@sambarnes You are right. `Abs(y - y' ) < maxerror)`. That is the constraint.

**Comment by sambarnes** [comment]
That would make sense, because if there is error between `x` and `x'`, and `y'` is computed from the already errored `x'`, I would expect `y'` to be different from `y`.

But this leads me to question the value of even doing the `x' --> y'` conversion, or if it is simply exercising the same issue again.

**Comment by Emyrk** [comment]
I didn't spend as much time as I'd like, but I think the `maxerror` can actually be smaller than my original equation if the ratio is `> 1`.

If the ratio is `> 1`, then you never get the partial input to 0 output problem. Meaning all your error comes from the truncation (max error of 1). If the ratio is `< 1`, then your max error is `(1 / ratio) + 1` (that plus one might actually be unnecessary too, now that I think about it).

So I think there is value is going both ways, but we can actually make the expected error function a bit tighter.

```
func maxConversionError(x, y uint64) int64 {
	if x == 0 || y == 0 {
		return 1
	}

        // Assuming the rates are passed in, in order of the `fromrate` -> `torate`. So the error
        // on one of the equation halves is much less. 
	if x > y {
		return 1
	}

	....
}
```

**Comment by sambarnes** [comment]
@Emyrk I don't believe that is correct.

I have updated the code with the proposed tightening and it fails the majority of random cases, and not just an off-by one error. Will look into it more

```go
...
func TestConversions_Convert_Random(t *testing.T) {
	for i := 0; i < 100; i++ {
		expectedErrorString := ""
		xRate := rand.Uint64() % (1e5 * 1e8) // Arbitrary maximum rate of $100k USD per unit
		yRate := rand.Uint64() % (1e5 * 1e8)
		if xRate == 0 || yRate == 0 {
			expectedErrorString = "invalid rate: 0"
		}
		x1 := rand.Int63n(1e9 * 1e8) // Arbitrary maximum of 1 billion units
		t.Run(fmt.Sprintf("Iteration %d", i), func(t *testing.T) {
			assert := assert.New(t)

			y1, err := Convert(x1, xRate, yRate)
			if len(expectedErrorString) != 0 {
				assert.EqualError(err, expectedErrorString)
				return
			}
			require.NoError(t, err)

			// Due to truncation in integer division, there is often error present in the
			// conversion from Y back to X. Thus, we check that it is within the expected
			// margin of error.
			x2, err := Convert(y1, yRate, xRate)
			require.NoError(t, err)
			observedError := abs(x1 - x2)
			maxExpectedError := maxConversionError(yRate, xRate)
			assert.True(observedError <= maxExpectedError, "Margin of error exceeded for Y1 --> X2: observedError=%d, maxError=%d", observedError, maxExpectedError)

			y2, err := Convert(x2, xRate, yRate)
			require.NoError(t, err)
			observedError = abs(y1 - y2)
			maxExpectedError = maxConversionError(xRate, yRate)
			assert.True(observedError <= maxExpectedError, "Margin of error exceeded for X2 --> Y2: observedError=%d, maxError=%d", observedError, maxExpectedError)
		})
	}
}

func maxConversionError(fromRate, toRate uint64) int64 {
	if fromRate == 0 || toRate == 0 || toRate < fromRate{
		return 1
	}
	fromRateBig := big.NewInt(0).SetUint64(fromRate)
	toRateBig := big.NewInt(0).SetUint64(toRate)

	ratioFromTo := big.NewInt(0).Div(fromRateBig, toRateBig)
	ratioToFrom := big.NewInt(0).Div(toRateBig, fromRateBig)
	if ratioFromTo.Cmp(ratioToFrom) == -1 {
		return ratioToFrom.Int64() + 1
	}
	return ratioFromTo.Int64() + 1
}
...
```
