### ISSUE TITLE
Large OPR count spikes / too many OPRs per block

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#310]
There have been a few events of multi-thousand OPRs submitted in a single block or unexpectedly large counts:

```
BLOCK   OPRS
-----------------------
210535  1519 (overflow) 
210534  4752 

210393   368

210335   468
210334   324
210333   336
210332   460
210331  4356
------------------- 210330 was the v2 activation height
210329  4643

210198  2010
```

We need to find out what caused this and then prevent it from happening again. Miners self-limit based on the expected difficult of the previous block, so that should be the first place to look.

**Comment by WhoSoup** [comment]
Here's the numbers for the four large sets

## Height 210198
Hash: 77c51ec855bf474a4a9a90320655ac325caff976ebb2eff207440bd29cdf3683
Entries: 2010

|Prefix|Entries|Miners|Max Individual|
|---|---|---|---|
|MaxCollabMiner|940|-|-|
|PrestigeMining|885|177|32|
|QWE|88|4|26|
|free|48|16|3|
|lm|16|11|3|
|ATB|10|-|-|
|AWSC5J|3|-|-|
|ActionManBowties|3|-|-|
|ECFutureJuice|3|-|-|
|facodo|3|-|-|
|Kmpndm|2|-|-|
|ZD|2|-|-|
|flappyK|2|-|-|
|KUNKA|1|-|-|
|Kompendium|1|-|-|
|flappyrvc|1|-|-|
|guizhou|1|-|-|
|lm00n|1|-|-|

## Height 210329
Hash: e54a5d7695e53d1b2f03cb76533c468905e36bc211fe390859d2680bfcf92a40
Entries: 4643

|Prefix|Entries|Miners|Max Individual|
|---|---|---|---|
|PrestigeMining|3164|323|192|
|MaxCollabMiner|940|-|-|
|AH|171|57|3|
|QWE|88|4|26|
|free|45|15|3|
|lm|36|13|3|
|fccentral|30|-|-|
|rayzenpegnet|30|-|-|
|StakeCapital|20|2|10|
|guizhou|12|4|3|
|ATB|10|-|-|
|MG|9|3|3|
|flappyMain|9|-|-|
|Eu4DVCKNM|6|2|3|
|KUNKA|6|2|3|
|flappyp|6|2|3|
|ECFutureJuice|5|2|1|
|Xeon|4|-|-|
|i|4|2|2|
|AWSC5J|3|-|-|
|ActionManBowties|3|-|-|
|ConsensusNetworksChain|3|-|-|
|FederateThis|3|-|-|
|MENGGU|3|-|-|
|Odn|3|-|-|
|PeggedByFCT|3|-|-|
|Sahara|3|-|-|
|flappy|3|3|3|
|fr|3|16|3|
|fr56g|3|-|-|
|free123234424fw|3|-|-|
|lm00n|3|-|-|
|mg|3|-|-|
|ElectroPi|2|-|-|
|Kmpndm|2|-|-|
|facodo|1|-|-|
|rpi|1|-|-|

## Height 210331
Hash: a952a39d7c979bf6990723d9acb4d1a112fd8c832afa21abe5f25e83ffcbde32
Entries: 4356

|Prefix|Entries|Miners|Max Individual|
|---|---|---|---|
|PrestigeMining|3165|325|192|
|MaxCollabMiner|940|-|-|
|QWE|88|4|26|
|lm|36|13|3|
|StakeCapital|30|3|10|
|guizhou|12|4|3|
|DFM|10|-|-|
|MG|9|3|3|
|flappyMain|9|-|-|
|KUNKA|6|2|3|
|flappyp|6|2|3|
|ActionManBowties|3|-|-|
|ConsensusNetworksChain|3|-|-|
|FederateThis|3|-|-|
|MENGGU|3|-|-|
|PeggedByFCT|3|-|-|
|Sahara|3|-|-|
|facodo|3|-|-|
|flappy|3|3|3|
|fr56g|3|-|-|
|free|3|-|-|
|free123234424fw|3|-|-|
|lm00n|3|-|-|
|mg|3|-|-|
|AWSC5J|2|-|-|
|fr|2|2|3|
|Kmpndm|1|-|-|
|Kompendium|1|-|-|

## Height 210534
Hash: 0b82a523ed12d8e3bfdb34fc1d0df33ffc7af823fcdc90131414ef240c313f8c
Entries: 4752

|Prefix|Entries|Miners|Max Individual|
|---|---|---|---|
|PrestigeMining|3264|346|190|
|MaxCollabMiner|940|-|-|
|AH|171|57|3|
|QWE|78|3|26|
|free|33|11|3|
|lm|33|12|3|
|StakeCapital|30|3|10|
|fccentral|30|-|-|
|rayzenpegnet|30|-|-|
|guizhou|15|5|3|
|ATB|10|-|-|
|DFM|10|-|-|
|Miner|10|-|-|
|pegnet|10|2|7|
|Eu4DVCKNM|9|3|3|
|MG|9|3|3|
|flappyMain|9|-|-|
|KUNKA|6|2|3|
|flappyp|6|2|3|
|ActionManBowties|3|-|-|
|ConsensusNetworksChain|3|-|-|
|FederateThis|3|-|-|
|MENGGU|3|-|-|
|Sahara|3|-|-|
|flappy|3|4|3|
|flappyL|3|-|-|
|flappyNuc|3|-|-|
|flappyRoot|3|-|-|
|flappybrd|3|-|-|
|flappyn|3|-|-|
|flappyrvc|3|-|-|
|lm00n|3|-|-|
|mg|3|-|-|
|theoriedesnombres|3|-|-|
|facodo|2|-|-|
|flappyK|2|-|-|

**Comment by PaulBernier** [comment]
Thanks for creating the issue and gathering the data. Steven found the root cause and fixed it here: https://github.com/pegnet/pegnet/pull/312/

**Comment by Emyrk** [comment]
Addressed https://github.com/pegnet/pegnet/pull/312
