### ISSUE TITLE
Use proper retry strategy when inserting data into Factom

### ISSUE THREAD

**Issue by PaulBernier** [pegnet/pegnet#44]
https://github.com/pegnet/pegnet/blob/master/opr/oneminer.go#L55
That loop hammers the factomd endpoint. A proper retry strategy needs to be implemented to avoid overwhelming the node. https://github.com/cenkalti/backoff is the kind of library that should be used.

**Comment by PaulSnow** [comment]
First I'll add a sleep so it doesn't hammer... And add logging to track the frequency this happens.  I suspect it doesn't really happen anywhere near enough to collect the data needed by the backoff algorithm.  However we have many other processes in factomd that could use the backoff algorithm to time frequency of requests, so this is pretty useful at least in concept.

**Comment by gunsmoke** [comment]
@PaulBernier can you review the PR https://github.com/pegnet/pegnet/pull/66 ?

**Comment by gunsmoke** [comment]
@PaulBernier can we close this?

**Comment by PaulBernier** [comment]
Yep
