### ISSUE TITLE
Calculating Grade doesn't reset

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#58]
https://github.com/pegnet/pegnet/blob/98e38066d1091497a45bdd2bdf1f79e54c33a434/opr/grading.go#L40-L47

Every cycle, the algorithm is supposed to take the average and move outliers to the back, however the **Grade doesn't reset between cycles** and it compounds. This can lead to fairly easy manipulation.

Assuming you have 10 records of $1, one record of $20, and one record of $1,000,000. In theory, the ten records of $1 should be selected but instead the algorithm picks $20 as the winner with nine 1$ entries. 
```
First Cycle:
Average = ($10 + $20 + $1,000,000) / 12 = $83335.833...

Results after first cycle:
$20 grade = 0 + (20-83335.833)^4 ~= 48184e15
nine times $1 grade = 0 + (1 - 83335.833)^4 ~= 48228e15
$1m grade = 0 + (1m - 83335.833)^4 = 706059041e15

Second Cycle:
Average = $30 / 11 = 2.727272...

Results:
$20 grade = 48184e15 + (20 - 2.72)^4 ~= 48184e15 + 89010
nine times $1 grade = 48228e15 + (1 - 2.72)^4 ~= 48228e15 + 8
```

Grade absolutely has to be reset between each cycle:

```go
func CalculateGrade(avg [20]float64, opr *OraclePriceRecord) float64 {
	tokens := opr.GetTokens()
	opr.Grade = 0
	for i, v := range tokens {
		d := v.value - avg[i]           // compute the difference from the average
		opr.Grade = opr.Grade + d*d*d*d // the grade is the sum of the squares of the differences
	}
	return opr.Grade
}
```

**Comment by PaulBernier** [comment]
@PaulSnow yes please describe that problem in another issue. I am resolving that one as I merged the PR into develop.
