### ISSUE TITLE
Grading should take the difference as a percent

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#60]
Right now the difference in grading is an absolute.  But a difference of 1 is very different if you are talking about an asset worth $1 from an asset worth $10,000.

Solution is to take a percentage difference from the average rather than an absolute difference

**Comment by MitchellBerry** [comment]
This issue has been fixed.

https://github.com/pegnet/pegnet/blob/e950f5cfbb7560a6d6d8529944cbbf23d8ea9260/opr/grading.go#L52-L53

`(v - avg ) / avg`

With $1000 avg and $1010 value:

`(1010 - 1000) / 1000 = 1`

With $100 avg and $101 value:

`(101 - 100) / 100 = 1`

**Comment by PaulBernier** [comment]
That's right. Closing.
