### ISSUE TITLE
Monitor Implementation

### ISSUE THREAD

**Issue by WhoSoup** [pegnet/pegnet#65]
https://github.com/pegnet/pegnet/blob/4b9d0d5f72dcdf5105415560519d7007d564ae29/common/monitor.go#L13

Two observations:
1. The monitor is never stopped
2. There's only one monitor instance that runs single threaded.

It is possible to just make it a singleton.

There's a lot of superfluous functionality (like stopping) and mutex juggling. I don't think mutexes are even necessary in this case, since the info struct is just swapped out with a new one but there are no goroutines that write data to the fields itself.

Is the stop functionality ever needed in theory? The only instance I can think of is if you hotswap the factomd connection during runtime to a different node that potentially has difference issues with directoryblockheights, but that seems a far fetched scenario. 

Any objections to a slight of this file to reduce mutexes?

**Comment by MitchellBerry** [comment]
Support this. Could certainly do with a trim.
Was originally pulling from the struct to serve up stats but the data is duplicated elsewhere and much more accessible.

**Comment by WhoSoup** [comment]
closing this issue since the pr was merged. thanks everyone!
