### ISSUE TITLE
Remove spaces from the Oracle Price Record chain

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#81]
To limit confusion, I believe that chain names we use in the PegNet should not include spaces.  Nor should they include characters outside of A-Z a-z 0-9.

This limits confusion about chainIDs when we see PegNet-TestNet-Oracle_Price_Records
This is easily a ChainID created from three fields, PegNet and TestNet and Oracle_Price_Records.

**Comment by WhoSoup** [comment]
Agreed!
