### ISSUE TITLE
Repair the Monitor

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#82]
Add the backoff call, repair and simplify the monitor

**Comment by PaulSnow** [comment]
Add a channel to log the subscription for alerts with the Monitor, which gets rid of other synchronization.
Add backoff call to get the current minute.
Remove unused accessors that shouldn't exist anyway, and are not used.

**Comment by PaulBernier** [comment]
Backoff is already there. @WhoSoup made a great job at simplifying the code already. Can you point more precisely to pieces of code you wish to rework?

**Comment by PaulSnow** [comment]
just dump.  Had not refreshed develop.
