### ISSUE TITLE
Remove init prints

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#87]
Currently running the pegnet cli, we always get prints from init functions in the various packages.

```
2019-07-16 19:23:52.647666143 -0500 CDT m=+0.002079765
Reading ByteMap Table  /home/steven/.lxrhash/lrxhash-seed-fafaececfafaecec-passes-5.size-25.dat

```

**Comment by MitchellBerry** [comment]
This is occurring in the LXRHash repo, and probably the bigger issue is that the hashmap is being initialised for cli calls.

**Comment by MitchellBerry** [comment]
Actually the first timestamp is from here: https://github.com/pegnet/pegnet/blob/28078c9a2a6e7c1dcef50e421522a7ab14e7c960/common/log.go#L21-L24

**Comment by WhoSoup** [comment]
> This is occurring in the LXRHash repo, and probably the bigger issue is that the hashmap is being initialised for cli calls.

related issue: https://github.com/pegnet/LXRHash/issues/25

**Comment by Emyrk** [comment]
https://github.com/pegnet/pegnet/pull/119
