### ISSUE TITLE
`Pegnet` Command Miner/API/CLI Organization

### ISSUE THREAD

**Issue by Emyrk** [pegnet/pegnet#92]
Currently to launch a miner you do `pegnet`, which then reads from the config file to find the number of miners to run. But this is also our cli tool, and soon to be api.

Would you guys be opposed to doing:
`pegnet --service miner --service api` to launch a miner with an api?

then when we add a control panel (if we will?)
`pegnet --service miner --service api --service controlpanel` (or something)
I would also allow the user to define the main-service that takes the main thread, in case for w/e reason they want that.
`pegnet --main-service miner --service api --service controlpanel`
My only concern is that it's not the most intuitive, as I can't think of another app that does this. It's kind of a result of us overloading the `pegnet` binary as being both the cli and the daemon.

I'd rather `pegnet` just display the help of all the available commands, similar to how if you use `docker`.

Does anyone want to defend just launching it as `pegnet` like it is now?

**Comment by MitchellBerry** [comment]
Certainly agree without anything else it should simply print out the help page, fairly standard behavior. Just launching it as is now doesn't feel right, especially with other commands: burn etc. 

The `--service` part seems a bit redundant? (And long to type out) 

Perhaps make the miner a command rather than flag? Guess could get a optional argument in then too. Maybe something like `pegnet mine` to use the config settings or `pegnet mine 12` for 12 miners.

Being able to specify the api or controlpanel seems prudent, people may not want them at all.

**Comment by MitchellBerry** [comment]
Right now the default of no miners gets overridden by the config here: https://github.com/pegnet/pegnet/blob/5abed24b56fb7706a59a54c3cee6e2846b494261/cmd/root.go#L64-L67

`LXRHash.Init()` function should probably be called root.go somewhere too whether or not mining is specified. It shouldn't be getting called unless necessary. A person without the bytemap will have to wait until it's generated first to simply use other commands.

**Comment by Emyrk** [comment]
> Certainly agree without anything else it should simply print out the help page, fairly standard behavior. Just launching it as is now doesn't feel right, especially with other commands: burn etc.
> 
> The `--service` part seems a bit redundant? (And long to type out)
> 
> Perhaps make the miner a command rather than flag? Guess could get a optional argument in then too. Maybe something like `pegnet mine` to use the config settings or `pegnet mine 12` for 12 miners.
> 
> Being able to specify the api or controlpanel seems prudent, people may not want them at all.

Something like that makes sense. I'm not married to how to launch the miner, just to make it not `pegnet`

**Comment by Cahl-Dee** [comment]
Will be addressed in the Node effort - #239
