### ISSUE TITLE
Bump the bits for BitMap from 25 to 30

### ISSUE THREAD

**Issue by PaulSnow** [pegnet/pegnet#93]
I think the consensus is in support of 30 bits (1 GB) for the ByteMap.

**Comment by PaulBernier** [comment]
Agreed here.

**Comment by PaulSnow** [comment]
So Develop didn't get a gofmt on the code.
So we have that.
And the go lint flagged some dead code and other minor issues.
So we have that.

**Comment by PaulBernier** [comment]
I think this issue was actually for the other LXR repo and that was done here: https://github.com/pegnet/LXRHash/commit/038e362dab0ddec62429a3e3cf7c671d1b62b2ef
Clsing.
